---
name: CI Update
on:
  workflow_dispatch:
    inputs:
      all_branches:
        description: "Run on all branches"
        default: 'no'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Run update
        run: |
          REPOS=(
            "pulpcore"
            "pulp_file"
            "pulp_rpm"
            "pulp_container"
            "pulp_ansible"
            "pulp_deb"
            "pulp-certguard"
            "pulp-2to3-migration"
            "pulp_python"
            "pulp_ostree"
            "pulp_npm"
            "pulp_maven"
            "pulp_gem"
            "pulp_cookbook"
          )
          echo "{\"ref\": \"main\", \"all_branches\": \"${{ github.event.inputs.all_branches }}\"}" > data.json
          for repo in "${REPOS[@]}"; do
              echo "Updating ${repo}..."
              curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/pulp/${repo}/actions/workflows/update_ci.yml/dispatches" \
              -d @data.json
          done
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
